### ISSUE TITLE
[bug] Ive downloaded the Plugin and theres no Settings or Hotkeys

### ISSUE THREAD

**Issue by CrackheadoooObsidianUserooo** [edonyzpc/personal-assistant#132]
Ive downloaded the Plugin and i cant do anything except use the personal assistant to disable or enable plugins via icon on the sidebar. Ive 
1. used another pc with a fresh vault
2. used brat instead of the community vault.

I have no clue what i am missing. But unfortunately cant i use the plugin as i want to.

**Comment by edonyzpc** [comment]
Thank you for reporting. Please let me know the version of this plugin you are using and you can use `show debug info` in the command palette to get this information.
<img width="714" alt="image" src="https://github.com/edonyzpc/personal-assistant/assets/7744664/8025ff84-2689-4505-9766-6be4c4ff500c">

And please check the usage which might be helpful:
1. search `switch plugin` in the command palette to the plugin switcher
<img width="731" alt="image" src="https://github.com/edonyzpc/personal-assistant/assets/7744664/15cf1882-0bf8-4340-ad2c-d9963e5da303">

2. trigger the command and find the plugin that you want to switch on/off(green means enabled and red means disabled)
<img width="738" alt="image" src="https://github.com/edonyzpc/personal-assistant/assets/7744664/2e61c1c8-3fe1-4e86-9f06-ca4024f2133c">

3. of course you can set hotkey for the command
<img width="1153" alt="image" src="https://github.com/edonyzpc/personal-assistant/assets/7744664/f64dccf8-046d-44e8-a9a0-0602ac8c4d73">

**Comment by CrackheadoooObsidianUserooo** [comment]
Im using the 1.24 version

the debug info 

SYSTEM INFO:
	Obsidian version: v1.3.7
	Installer version: v1.3.5
	Operating system: Windows 10 Home 10.0.22621
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 32
	Restricted mode: off
	Plugins installed: 104
	Plugins enabled: 93
		1: Hover Editor v0.11.12
		2: Admonition v9.3.2
		3: Auto Note Mover v1.2.0
		4: Better footnote v1.0.1
		5: Breadcrumbs v3.6.4
		6: Chorded Hotkeys v1.0.0
		7: Citations v0.4.5
		8: Copy Block Link v1.0.4
		9: Custom Frames v2.4.6
		10: Customizable Menu v2.2.0
		11: Dataview v0.5.56
		12: DB Folder v3.4.0
		13: Zotero Integration v2.3.9
		14: Vimrc Support v0.9.0
		15: Timestamp Notes v1.0.8
		16: Tidy Footnotes v0.1.1
		17: Text Extractor v0.4.6
		18: Templater v1.16.0
		19: Tasks v4.0.1
		20: Tag Wrangler v0.5.11
		21: Tag Search v1.2.1
		22: Style Settings v1.0.6
		23: Smarter Markdown Hotkeys v1.16.4
		24: Recent Files v1.3.6
		25: QuickAdd v1.2.1
		26: Quick Explorer v0.2.8
		27: Projects v1.16.0
		28: Plugin Update Tracker v1.5.1
		29: Plugin Groups v2.1.0
		30: Pending notes v0.6.2
		31: Pane Relief v0.5.0
		32: Outliner v4.7.1
		33: Obsidian42 - Strange New Worlds (SNW) v1.2.2
		34: Omnisearch v1.14.2
		35: Obsidian42 - BRAT v0.7.0
		36: Obsidian Stylist v0.0.4
		37: obsidian markmind v1.7.4
		38: Obsidian Better Internal Link Inserter v1.0.0
		39: Note Refactor v1.7.1
		40: Note aliases v1.2.0
		41: Multi-Column Markdown v0.8.3
		42: Mind Map v1.1.0
		43: Media Extended v2.11.1
		44: Linter v1.16.0
		45: Link Headers Directly v1.0.2
		46: Lapel v0.1.1
		47: Kindle Highlights v1.9.2
		48: Jump to link v0.4.4
		49: Juggl v1.4.0
		50: Image Toolkit v1.3.1
		51: Global Search and Replace v0.3.0
		52: Front Matter Title v3.3.1
		53: Footnote Shortcut v0.1.2
		54: Floating Search v3.3.1
		55: Flexdown Plugin v1.0.0
		56: Fleeting Notes Sync v0.6.1
		57: Flashcards v1.6.5
		58: File Hider v1.1.1
		59: Excalidraw v1.9.6
		60: ExcaliBrain v0.1.15
		61: Editor Syntax Highlight v0.1.3
		62: Duckbase Plugin v1.0.1
		63: OZ Calendar v0.2.9
		64: Update time on edit v1.1.2
		65: Tray v0.3.3
		66: Completr v3.2.0
		67: Home tab v1.1.2
		68: Hotkeys for specific files v1.3.1
		69: Quiet Outline v0.3.15
		70: Obsidian Git v2.20.4
		71: Workspaces Plus v0.3.3
		72: Homepage v3.3
		73: Askify Sync v1.0.0
		74: YTranscript v0.8.2
		75: Fullscreen mode plugin v0.1.2
		76: Vim Toggle v1.0.6
		77: File path to URI v1.4.1
		78: MAKE.md v0.7.18
		79: Code Editor Shortcuts v1.14.0
		80: Surfing Key v0.0.1
		81: Webpage HTML Export v1.6.0
		82: Automatic List Styles v0.1.0
		83: Omnivore v1.5.3
		84: Highlightr v1.2.2
		85: Advanced Tables v0.18.1
		86: Dashboards v6.19.1
		87: Various Complements v8.3.1
		88: Chronology v1.1.4
		89: Link Exploder v0.2.5
		90: Navigate Cursor History v1.1.0
		91: Remember cursor position v1.0.7
		92: Commander v0.5.0
		93: Personal Assistant v1.2.4

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.


![image](https://github.com/edonyzpc/personal-assistant/assets/121588624/fcb4a624-40a0-431f-96c3-345b6c5fa858)


i have the plugin enabeld but cant choose any hotkeys

**Comment by edonyzpc** [comment]
@CrackheadoooObsidianUserooo the default setting is to blame. And please upgrade to v1.2.5 to check if it works.
