### ISSUE TITLE
[feat] 接入obsdian情绪追踪器插件

### ISSUE THREAD

**Issue by aiyou9** [edonyzpc/personal-assistant#193]
## Description
作为个人助手，应该支持情绪追踪，obsdian有这个插件，https://github.com/dartungar/obsidian-mood-tracker  它以json保存数据，还有图表显示，参考的是 个人生产力提升工具 https://amazingmarvin.com/
## Tasks
- [ ] taks1

**Comment by edonyzpc** [comment]
当前插件的定位还是通过自动化将用户从 Obsidan 的管理中解脱出来，不知道你提到的 Mood Tracker 还有什么地方无法满足你的需求，可以试着看看有哪些可以通过自动化解决追踪心情的场景或需求，这样的 Personal Assistant 可以更加快速地实现对应的 FR。

_**P.S.**_ 我个人感觉你的需求跟 Obsidian Memo 更加契合，不知道是否有了解过，特别是 Memo 2.0 版本做得非常好，更加对标你提到的 MARVIN，2.0的功能、UI、交互等都实现得更加优雅和便捷。当前还在内测中，内测版本可以联系 @[Quorafind](https://github.com/Quorafind)  获取。

**Comment by aiyou9** [comment]
> 

1、你这一说，我懂了，是我需求不明确，我参加了memos 2.0的 众筹，在等新版本发布
2、我可能是，最想要的是，数据图表面板，看您博客里有介绍，很炫酷，哈哈

**Comment by edonyzpc** [comment]
@aiyou9 感谢🙏你的issue，我了解你提需求的原因了，我非常赞同数据展示确实是一个不错的管理场景，我最近打算添加一个新的 feature，参考这个 https://github.com/edonyzpc/personal-assistant/issues/194
