### ISSUE TITLE
[help] Unsolicited advice about usability and better Readme.

### ISSUE THREAD

**Issue by ksdavidc** [edonyzpc/personal-assistant#255]
## Description
Very hard to tell what this plugin does. Your descriptions assume we know what you mean. the videos are 1. too fast, 2. lack explanation and context.

- The "features" section of the readme IMHO should be at the top, because the videos are not sufficiently clear, and require me to watch the entire video (which loops, so I don't actually know where it starts, hence can't understand what it does)

## automatically create note in the specified directory with the configured file name

- need to mention that 1. you need to set this up in the settings first. You need to add an *existing* folder to the settings. (it seems clear that one must also add a date or other format). 
- It is not clear what you mean by record. Is this an audio recording? A "record" as is a kind of proof that something was done? Or as I suspect, but am not sure, simply similar functionality to what a daily notes provides, a kind of log? 
- Except you are providing some kind of "preview" for this with a fixed number of recent entries visible.
- Just what is the use case (i.e. when would you use this and how?)
- How does it differ from Daily notes?

## automatically open current note related graph view
- this makes sense, but no video provided

## automatically open Memos like quick note in macOS
- Do you mean Memos, the plugin that was recently renamed Thino, or Memos, the notetaking app, that is not related to Obsidian?
- not sure what this does, and it did nothing. Needs further instructions.

## switch on/off plugin in command palette
duplicate of obsidan plugin manager

## automatically update plugins with one command
similar to plugin updater

## automatically update themes with one command
sounds good

## automatically set color of graph view
screenshot would be nice

## list all callouts css configuration for quickly inserting
duplicate/similar to callout suggester plugin

**Comment by edonyzpc** [comment]
@ksdavidc Oh, that's so kind of you. Thank you for your detailed and valuable feedback. I'll try to improve the document accordingly. Including some tutorial videos would indeed be better for users, and I'm working on that.

**Comment by edonyzpc** [comment]
close with #256 
@ksdavidc Thank you for your help. And if you have anything, feel free to submit issue.
