### ISSUE TITLE
[help]When I try to use the “Personal Assistant:List callout for quickly insert” command directly, there is only a “quote” category.

### ISSUE THREAD

**Issue by miss66kill66** [edonyzpc/personal-assistant#258]
## Description
When I try to use the “Personal Assistant:List callout for quickly insert” command directly, there is only a “quote” category.
当我想直接使用"Personal Assistant:List callout for quickly insert" 命令的时候，里面只有一个"quote"类别，并没有出现所有的callout类型

Why is it that I don't have as many callout types when I use it as demonstrated in the README
为什么我在使用的时候并没有像README中所演示的那样，有很多callout类型，是哪里设置不对吗？

![5kctwieWfY](https://github.com/user-attachments/assets/8b264c98-26d8-4df1-be63-8c3c60f9b5ff)
![image](https://github.com/user-attachments/assets/847967c3-72ee-4a53-924c-95cc3e8bfd69)

**Comment by edonyzpc** [comment]
@miss66kill66 确认一下 callout manager 插件的检测 callout 的配置是否都打开了
<img width="840" alt="image" src="https://github.com/user-attachments/assets/84f4a410-80a9-4dc2-a120-34c89e2c7c3b">

然后manage callout查看是否检测成功
<img width="848" alt="image" src="https://github.com/user-attachments/assets/079fee21-c416-4e6d-91cc-94786b12dfd6">
<img width="830" alt="image" src="https://github.com/user-attachments/assets/10f84451-1d4a-4a2e-b529-30eedd1dee41">

**Comment by miss66kill66** [comment]
解决了，确实是callout manager的问题，感谢大佬抽空解答🍕
