### ISSUE TITLE
[feat] 插件启用/停用的命令支持单次多个勾选/取消

### ISSUE THREAD

**Issue by Royalsus** [edonyzpc/personal-assistant#268]
## Description
当前命令一次只能修改一个插件的启用/停用，无法一次多选，有点不够方便
### Requirement/Scenario
希望能支持多个勾选/取消，关闭窗口时统一生效
## Tasks
- [ ] taks1

**Comment by edonyzpc** [comment]
下个版本我增加一个批量处理的功能
