### ISSUE TITLE
[feat]开关插件的窗口增加搜索功能、建议只需要一个窗口控制插件的开关

### ISSUE THREAD

**Issue by kickTiger** [edonyzpc/personal-assistant#73]
1、建议：在开关插件窗口增加搜索功能。一个个下拉太慢了，尤其是插件比较多的时候。
2、建议：一个窗口控制开关。个人觉得不需要两个命令窗口，太繁琐了。
直接在一个窗口去开关插件，在插件名称上，用上emoji图标显示下开关的状态就可以了。
3、建议：新建笔记的时候，可以选择指定的模板，不然空白文件太简单了

**Comment by kickTiger** [comment]
另外建议取消打开obsidian时候的，右侧顶上的提醒消息。

谢谢！

**Comment by edonyzpc** [comment]
感谢提供非常好的建议，我总结一下：
1. 插件开关支持关键字检索；
2. 插件开关命令进行归一；
3. 去掉插件启动通知

P.S. 模版那个问题建议使用 templater 的 Folder Templates

**Comment by kickTiger** [comment]
感谢,这个模板插件的功能看过,没想到这么用🤩。

**Comment by edonyzpc** [comment]
feature request 已经发布，参考版本 [1.1.0](https://github.com/edonyzpc/personal-assistant/releases/tag/1.1.0)。

关闭该 issue
